### ISSUE TITLE
感谢大佬开源！小程序已上线，还在参考大佬源码增加其它功能，欢迎围观。

### ISSUE THREAD

**Issue by aberlt** [SunJackson/coupons-ss#1]
![gh_339364c67e98_258](https://user-images.githubusercontent.com/9360124/105378029-5d6fb480-5c46-11eb-8f41-57ab1e4787e2.jpg)

**Comment by chofan007** [comment]
你好，能加个好友吗？

**Comment by aberlt** [comment]
> 你好，能加个好友吗？

有什么问题吗？

**Comment by chofan007** [comment]
您好，想请教一下微信小程序的问题，自己想弄一个，不会代码，很艰难！

**Comment by aberlt** [comment]
> 您好，想请教一下微信小程序的问题，自己想弄一个，不会代码，很艰难！
> […](#)
> 在 2021年2月3日，14:17，aberlt ***@***.***> 写道： ﻿ 你好，能加个好友吗？ 有什么问题吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

别搞这个了，我的被人举报下架了

**Comment by chofan007** [comment]
好吧，不过微信上还是有很多这种小程序，用的人不多应该不影响吧，或者添加点运营主体




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aberlt"<notifications@github.com&gt;; 
发送时间: 2021年2月3日(星期三) 下午3:02
收件人: "SunJackson/coupons-ss"<coupons-ss@noreply.github.com&gt;; 
抄送: "陈"<794456035@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [SunJackson/coupons-ss] 感谢大佬开源！小程序已上线，还在参考大佬源码增加其它功能，欢迎围观。 (#1)





  
您好，想请教一下微信小程序的问题，自己想弄一个，不会代码，很艰难！
 …
 在 2021年2月3日，14:17，aberlt @.***&gt; 写道： ﻿ 你好，能加个好友吗？ 有什么问题吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
别搞这个了，我的被人举报下架了
 
&mdash;

**Comment by aberlt** [comment]
> 好吧，不过微信上还是有很多这种小程序，用的人不多应该不影响吧，或者添加点运营主体
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aberlt"<notifications@github.com&gt;; 发送时间: 2021年2月3日(星期三) 下午3:02 收件人: "SunJackson/coupons-ss"<coupons-ss@noreply.github.com&gt;; 抄送: "陈"<794456035@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [SunJackson/coupons-ss] 感谢大佬开源！小程序已上线，还在参考大佬源码增加其它功能，欢迎围观。 (#1) 您好，想请教一下微信小程序的问题，自己想弄一个，不会代码，很艰难！ … 在 2021年2月3日，14:17，aberlt @.***&gt; 写道： ﻿ 你好，能加个好友吗？ 有什么问题吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 别搞这个了，我的被人举报下架了 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我的日活还不到20，同行恶意举报，一报一个准。

**Comment by chofan007** [comment]
好吧，感谢回复，我自己琢磨琢磨，反正零投入




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aberlt"<notifications@github.com&gt;; 
发送时间: 2021年2月3日(星期三) 下午3:07
收件人: "SunJackson/coupons-ss"<coupons-ss@noreply.github.com&gt;; 
抄送: "陈"<794456035@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [SunJackson/coupons-ss] 感谢大佬开源！小程序已上线，还在参考大佬源码增加其它功能，欢迎围观。 (#1)





  
好吧，不过微信上还是有很多这种小程序，用的人不多应该不影响吧，或者添加点运营主体
 …
 ------------------ 原始邮件 ------------------ 发件人: "aberlt"<notifications@github.com&gt;; 发送时间: 2021年2月3日(星期三) 下午3:02 收件人: "SunJackson/coupons-ss"<coupons-ss@noreply.github.com&gt;; 抄送: "陈"<794456035@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [SunJackson/coupons-ss] 感谢大佬开源！小程序已上线，还在参考大佬源码增加其它功能，欢迎围观。 (#1) 您好，想请教一下微信小程序的问题，自己想弄一个，不会代码，很艰难！ … 在 2021年2月3日，14:17，aberlt @.***&gt; 写道： ﻿ 你好，能加个好友吗？ 有什么问题吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 别搞这个了，我的被人举报下架了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我的日活还不到20，同行恶意举报，一报一个准。
 
&mdash;
